version: 2

sources:
  - name: marts
    database: dataengcamp-427114
    schema: lending_club_bq
    tables:
      - name: lending_club_partitioned_clustered

models:
  - name: dim_loan
    description: "Extra loan information"
    columns:
      - name: loan_id
        data_type: string
        description: "Loan unique identifier"

      - name: purpose
        data_type: string
        description: "A category provided by the borrower for the loan request"

      - name: title
        data_type: string
        description: "The loan title provided by the borrower"

      - name: sub_grade
        data_type: string
        description: "Lending Club assigned loan subgrade"

  - name: dim_date
    description: "Extra loan date information"
    columns:
      - name: date_id
        data_type: string
        description: "Date unique identifier"

      - name: issue_d
        data_type: timestamp
        description: "The YYYY-MMM in which the loan was funded"

      - name: issue_year
        data_type: int64
        description: "The year in which the loan was funded"

      - name: issue_quarter
        data_type: int64
        description: "The quarter in which the loan was funded"

      - name: issue_month
        data_type: int64
        description: "The month in which the loan was funded"

  - name: dim_borrower
    description: "Extra borrower information"
    columns:
      - name: borrower_id
        data_type: string
        description: "Borrower unique identifier"

      - name: emp_title
        data_type: string
        description: "The job title supplied by the Borrower when applying for the loan"

      - name: emp_length
        data_type: string
        description: "Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years"

      - name: home_ownership
        data_type: string
        description: "The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER"

      - name: annual_inc
        data_type: float64
        description: "The self-reported annual income provided by the borrower during registration"

      - name: verification_status
        data_type: string
        description: "Indicates if income was verified by LC, not verified, or if the income source was verified"

      - name: address
        data_type: string
        description: "The state and zip code provided by the borrower in the loan application"
