version: 2

models:
  - name: dim_date
    description: "Extra loan date information"
    columns:
      - name: date_id
        data_type: string
        description: "Date unique identifier"
        tests:
          - not_null:
              severity: warn

      - name: issue_d
        data_type: timestamp
        description: "The YYYY-MMM in which the loan was funded"
        tests:
          - not_null:
              severity: warn

      - name: issue_year
        data_type: int64
        description: "The year in which the loan was funded"

      - name: issue_quarter
        data_type: int64
        description: "The quarter in which the loan was funded"

      - name: issue_month
        data_type: int64
        description: "The month in which the loan was funded"

  - name: dim_borrower
    description: "Extra borrower information"
    columns:
      - name: borrower_id
        data_type: string
        description: "Borrower unique identifier"
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: emp_title
        data_type: string
        description: "The job title supplied by the Borrower when applying for the loan"

      - name: emp_length
        data_type: string
        description: "Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years"

      - name: home_ownership
        data_type: string
        description: "The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER"

      - name: annual_inc
        data_type: float64
        description: "The self-reported annual income provided by the borrower during registration"
        tests:
          - not_null:
              severity: warn

      - name: verification_status
        data_type: string
        description: "Indicates if income was verified by LC, not verified, or if the income source was verified"

      - name: address
        data_type: string
        description: "The state and zip code provided by the borrower in the loan application"
  
  - name: fact_loans
    description: "Table including information from all tables"
    columns:
      - name: sub_grade
        data_type: string
        description: "Lending Club assigned loan subgrade"
        tests:
          - not_null:
              severity: warn

      - name: borrower_id
        data_type: string
        description: "Borrower unique identifier"

      - name: emp_title
        data_type: string
        description: "The job title supplied by the Borrower when applying for the loan"

      - name: emp_length
        data_type: string
        description: "Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years"

      - name: home_ownership
        data_type: string
        description: "The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER"

      - name: annual_inc
        data_type: float64
        description: "The self-reported annual income provided by the borrower during registration"

      - name: verification_status
        data_type: string
        description: "Indicates if income was verified by LC, not verified, or if the income source was verified"

      - name: address
        data_type: string
        description: "The state and zip code provided by the borrower in the loan application"

      - name: loan_amnt
        data_type: float64
        description: "The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value"
        tests:
          - not_null:
              severity: warn

      - name: int_rate
        data_type: float64
        description: "Interest Rate on the loan"
        tests:
          - not_null:
              severity: warn

      - name: term
        data_type: int64
        description: "The number of payments on the loan. Values are in months and can be either 36 or 60"

      - name: installment
        data_type: float64
        description: "The monthly payment owed by the borrower if the loan originates"

      - name: grade
        data_type: string
        description: "Lending Club assigned loan grade"

      - name: loan_status
        data_type: string
        description: "Current status of the loan"

      - name: date_id
        data_type: string
        description: "Loan issue date unique identifier"
        tests:
          - not_null:
              severity: warn

      - name: issue_d
        data_type: timestamp
        description: "The YYYY-MMM in which the loan was funded"

      - name: issue_year
        data_type: int64
        description: "The year in which the loan was funded"

      - name: issue_quarter
        data_type: int64
        description: "The quarter in which the loan was funded"

      - name: issue_month
        data_type: int64
        description: "The month in which the loan was funded"

      - name: dti
        data_type: float64
        description: "A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income"

      - name: earliest_cr_line
        data_type: timestamp
        description: "The month the borrower's earliest reported credit line was opened"

      - name: open_acc
        data_type: float64
        description: "The number of open credit lines in the borrower's credit file"

      - name: pub_rec
        data_type: float64
        description: "Number of derogatory public records"

      - name: revol_bal
        data_type: float64
        description: "Total credit revolving balance"

      - name: revol_util
        data_type: float64
        description: "Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit"

      - name: total_acc
        data_type: float64
        description: "The total number of credit lines currently in the borrower's credit file"

      - name: initial_list_status
        data_type: string
        description: "The initial listing status of the loan. Possible values are - W, F"

      - name: application_type
        data_type: string
        description: "Indicates whether the loan is an individual application or a joint application with two co-borrowers"

      - name: mort_acc
        data_type: float64
        description: "Number of mortgage accounts"

      - name: pub_rec_bankruptcies
        data_type: float64
        description: "Number of public record bankruptcies"

      - name: purpose
        data_type: string
        description: "A category provided by the borrower for the loan request"

      - name: title
        data_type: string
        description: "The loan title provided by the borrower"
